phprun5:
      build: images/php/5.6
      command: ['php','-S','127.0.0.1:8899','-t','/tmp/']
      volumes:
              - ~/php_develop:/php_develop
         
      privileged: true
      volumes: 
              - ./:/php_develop
              - ./conf.d/php56:/usr/local/etc/php/conf.d/
              - ./conf/php-5.6.27/php.ini-development:/usr/local/etc/php/php.ini
              - ./extension/php56/:/usr/local/lib/php/extensions/debug-zts-20131226
      # worker_dir: /php_develop/workbench
phprun7:
      build: images/php/7.0
      command: ['php','-S','127.0.0.1:8899','-t','/tmp/']
 
      volumes:
              - ./:/php_develop
              - ./conf.d/php70:/usr/local/etc/php/conf.d
              - ./extension/php70/:/usr/local/lib/php/extensions/debug-non-zts-20151012/
              - ./conf/php-7.0.12/php.ini-development:/usr/local/etc/php/php.ini
      privileged: true
phprun71:
      build: images/php/7.1
      command: ['php','-S','127.0.0.1:8899','-t','/tmp/']

      volumes:
              - ./:/php_develop
              - ./conf.d/php71:/usr/local/etc/php/conf.d
              - ./extension/php71/:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/
              - ./conf/php-7.1.0/php.ini-development:/usr/local/etc/php/php.ini
              - ./workbench/php-7.1.0:/usr/src/php
      privileged: true    
      # worker_dir: /php_develop/workbench
