phprun5:
      build: images/php/5.6
      command: ['php','-S','127.0.0.1:8899','-t','/tmp/']
      volumes:
              - ~/php_develop:/php_develop
      ports:
              - "8897:8899"            
      privileged: true
      volumes: 
              - ./:/php_develop
              - ./conf.d:/usr/local/etc/php/conf.d
              - ./conf/php-5.6.27/php.ini-development:/usr/local/etc/php/php.ini
phprun7:
      build: images/php/7.0
      command: ['php','-S','127.0.0.1:8899','-t','/tmp/']
      ports:
              - "8898:8899"
      volumes:
              - ./:/php_develop
              - ./conf.d:/usr/local/etc/php/conf.d
              - ./conf/php-7.0.12/php.ini-development:/usr/local/etc/php/php.ini
      privileged: true
